# Generated by Django 3.2.7 on 2021-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='posting',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
