# Generated by Django 3.2.8 on 2021-10-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=450)),
                ('address2', models.CharField(max_length=450, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
