# Generated by Django 3.2.8 on 2021-10-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_thumbnail_product_thumbnail_image_url'),
        ('orders', '0004_auto_20211012_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='color',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='size',
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.detailedproduct'),
        ),
    ]
