# Generated by Django 3.2.8 on 2021-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211012_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
