# Generated by Django 3.2.8 on 2021-10-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='urls',
            field=models.ImageField(max_length=700, upload_to=''),
        ),
    ]
