# Generated by Django 3.2.8 on 2021-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='urls',
            field=models.CharField(max_length=700),
        ),
    ]
